### ISSUE TITLE
siteUrl for thread comments is incorrect

### ISSUE THREAD

**Issue by markphilpot** [AniList/ApiV2-GraphQL-Docs#39] opened 2018-05-31 04:21 UTC
Example:

API returns `https://anilist.co/forum/comment/72410` which results in a 404

When the website url for the comment seems to be `https://anilist.co/forum/thread/2958/comment/72410`

The site url for threads seems to be correct.

**Comment by joshstar** [comment] 2018-06-02 03:47
Sorry about that, should be fixed now.

**Comment by markphilpot** [comment] 2018-06-02 04:30
notification queries that include `siteUrl` on both the thread and comment objects seem to be causing 500 errors on the server

**Comment by joshstar** [comment] 2018-06-03 11:14
Sorry for the issues! 
I think this should be fixed now, though I'm not sure exactly what you meant by the thread object causing a 500 as I couldn't reproduce that, but hopefully the comment siteUrl should be working at least now.

**Closed** 2018-06-13 02:13 UTC
Labels: Bug
