### ISSUE TITLE
A question about X-RateLimit-Remaining

### ISSUE THREAD

**Issue by Dazorn96** [AniList/ApiV2-GraphQL-Docs#103] opened 2020-11-06 09:02 UTC
Hi, I am using the GraphQL API with my C# application. I noticed a strange thing inside your response header `X-RateLimit-Remaining`. This is my query:
```
query($page: Int) {
    Page(page: $page, perPage: 50) {
        pageInfo {
            lastPage
        }
        media {
            id
            idMal
            format
            status
            startDate {
                year
                month
                day
            }
            endDate {
                year
                month
                day
            }
            title {
                romaji
                native
            }
            description
        }
    }
}
```
What I expect to receive after **one** query is `X-RateLimit-Remaining` equal to **89** because the whole query counts as **one request**, but I got a lower value between **70** and **80**.
What am I missing? Is this normal or am I doing something wrong?

Thanks

**Comment by mahkoh** [comment] 2020-11-19 11:50
I believe that this is a bug. I'm also writing an application that uses the graphql api and I'm making sure that I'm only performing at most one request per second. Yet I'm still hitting the limit. The following table contains the time of the request and the value of X-RateLimit-Remaining. This test was performed from a residential connection which is not behind NAT.  Maybe the anilist servers are getting confused by cloudflare?

```
12:40:06.698041753: 62
12:40:07.698108548: 60
12:40:08.698103137: 59
12:40:09.698105309: 58
12:40:10.698104706: 56
12:40:11.698134742: 55
12:40:12.698112559: 54
12:40:13.698111366: 53
12:40:14.698106035: 51
12:40:15.698108858: 50
12:40:16.698111132: 49
12:40:17.698111893: 48
12:40:18.698107173: 45
12:40:19.698111290: 89
12:40:20.698112211: 41
12:40:21.698112460: 88
12:40:22.698112900: 86
12:40:23.698113220: 85
12:40:24.698112969: 84
12:40:25.698113079: 83
12:40:26.698112467: 82
12:40:27.698112346: 81
12:40:28.698112685: 88
12:40:29.698107475: 79
12:40:30.698112985: 78
12:40:31.698111762: 77
12:40:32.698109918: 76
12:40:33.698116160: 75
12:40:34.698113124: 74
12:40:35.698113263: 72
12:40:36.698114776: 69
12:40:37.698112351: 66
12:40:38.698111119: 65
12:40:39.698112061: 64
12:40:40.698110467: 63
12:40:41.698112180: 62
12:40:42.698112611: 61
12:40:43.698131736: 60
12:40:44.698132067: 59
12:40:45.698136304: 57
12:40:46.698108492: 56
12:40:47.698110807: 55
12:40:48.698105667: 54
12:40:49.698110457: 53
12:40:50.698112771: 84
12:40:51.698109374: 52
12:40:52.698112952: 48
12:40:53.698110127: 47
12:40:54.698110678: 44
12:40:55.698108023: 43
12:40:56.698111280: 42
12:40:57.698111511: 39
12:40:58.698108796: 37
12:40:59.698131590: 34
12:41:00.698111041: 33
12:41:01.698105531: 32
12:41:02.698113145: 31
12:41:03.698123777: 29
12:41:04.698112536: 28
12:41:05.698113017: 27
12:41:06.698110773: 26
12:41:07.698107417: 25
12:41:08.698108660: 24
12:41:09.698131514: 22
12:41:10.698111998: 20
12:41:11.698111517: 19
12:41:12.698113161: 82
12:41:13.698100708: 18
12:41:14.698109997: 16
12:41:15.698109106: 12
12:41:16.698113384: 10
12:41:17.698104238: 9
12:41:18.698092667: 8
12:41:19.698121513: 6
12:41:20.698105162: 4
12:41:21.698104733: 89
12:41:22.698107058: 89
12:41:23.698105376: 88
12:41:24.698103153: 87
12:41:25.698106050: 86
12:41:26.698122983: 80
12:41:27.698104900: 79
12:41:28.698106334: 78
12:41:29.698101376: 77
12:41:30.698104623: 76
12:41:31.698094456: 75
12:41:32.698094957: 74
12:41:33.698104456: 73
12:41:34.698119156: 72
12:41:35.698125258: 71
12:41:36.698111855: 67
12:41:37.698135290: 64
12:41:38.698112258: 63
12:41:39.698111829: 61
12:41:40.698112181: 60
12:41:41.698111961: 58
12:41:42.698110941: 57
12:41:43.698112386: 56
12:41:44.698131083: 55
12:41:45.698132356: 53
12:41:46.698111188: 52
12:41:47.698111630: 51
12:41:48.698116842: 50
12:41:49.698112866: 49
12:41:50.698131093: 45
12:41:51.698131876: 44
12:41:52.698112170: 43
12:41:53.698132390: 38
12:41:54.698130980: 37
12:41:55.698112526: 36
12:41:56.698115714: 31
12:41:57.698112210: 86
12:41:58.698111841: 26
12:41:59.698111121: 23
12:42:00.698110893: 21
12:42:01.698112127: 19
12:42:02.698111598: 18
12:42:03.698112933: 16
12:42:04.698113977: 15
12:42:05.698111875: 14
12:42:06.698131924: 13
12:42:07.698112991: 12
12:42:08.698111641: 83
12:42:09.698112424: 11
12:42:10.698135390: 10
12:42:11.698111366: 8
12:42:12.698114695: 7
12:42:13.698131078: 6
12:42:14.698111403: 5
12:42:15.698113609: 4
12:42:16.698131335: 3
12:42:17.698109456: 2
12:42:18.698111303: 1
12:42:19.698110393: 0
12:42:20.698110485: 0
```

**Comment by LiteLT** [comment] 2020-11-21 16:52
I noticed a similar issue in my SwiftUI project. At first, it was caused by me sending multiple API requests, but after fixing that, I still noticed the `x-ratelimit-remaining` number not being consistent. I tried closing my app, browser tabs, and opening the console to send demo requests and wasn't able to reproduce it.

I do feel there's something weird going on.

**Comment by joshstar** [comment] 2020-11-23 12:45
Hey yeah thanks for bringing this up. I've been looking into this but haven't had much luck finding the cause just yet

**Comment by rangigo** [comment] 2020-11-23 14:26
I can take a look.

**Comment by Dazorn96** [comment] 2020-11-23 20:09
Hi all, after days of retrial i finally opted for a local implementation of the API calls (before i was using a third party library for GraphQL). I found out the lib were doing more calls for a single requests... what a crap.
By the way, regarding @LiteLT bug, i noticed that too... number are not consistents... sometimes all works good and other times i got things like:
```
...
60
59
58
80
79
78
...
```

**Comment by rangigo** [comment] 2020-12-21 11:49
@Dazorn96 can we close this now?

**Comment by joshstar** [comment] 2021-03-18 00:28
I made some changes last week which I think should have solved this issue for good. 
Do let me know if it pops up again though.

**Closed by joshstar** 2021-03-18 00:28 UTC
